version: '2.1'
orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@4.4.0
jobs:
  test:
    docker:
      - image: 'cimg/node:16.13.0'
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile
      - run:
          command: pnpm lint
          name: Run linter
      - run:
          command: pnpm test:cov
          name: Run tests
      - coveralls/upload
      - run:
          command: pnpm test:e2e
          name: Run e2e-tests
workflows:
  test_lib:
    jobs:
      - test